### ISSUE TITLE
automated download of fishbase/sealife preyvalues on species level

### ISSUE THREAD

**Issue by sofalbre** [sborstein/dietr#21]
Hello,

I'd like to use the package to calculate the trophic level of a dolphin species feeding on different fish and cephalopods. Would there be a way of automatised download of the trophic levels of the prey species trophic levels, instead of manually filling in the values?

For Sprat it would be for example  3.0   ±0.07 se https://fishbase.mnhn.fr/summary/SpeciesSummary.php?ID=1357&AT=sprat .

Cheers and thanks a million,
Sofia

**Comment by sborstein** [comment]
Hi Sofia,

Thanks for using `dietr`. The functionality to obtain FishBase trophic levels for species already exists with functions in the `rfishbase` package, so I will not implement it in this package and am therefore closing the issue. However, do be mindful that as FishBase is a large database, some errors may exist in the database, which is one of the reasons I created this package. You can always download the diet composition data using `rfishbase` and recalculte trophic level with `dietr` if needed.

Best,
-Sam

**Comment by sofalbre** [comment]
[like]  SOFIA ALBRECHT - RESEARCH reacted to your message:
________________________________
